#pragma config(Motor,  port2,           driveleft,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           driveright,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           liftleft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           liftright,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           flipmotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           armflip,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           claw,          tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	while(1==1)
	{

		motor[port2] = vexRT[Ch2];
		motor[port3] = vexRT[Ch3];

		if(vexRT[Btn8U] == 1)
		{
			motor[armflip] = 30;


		else if (vexRT[Btn8D] == 1)
		{
			motor[armflip] = -30;
		}

		else
		{
			motor[armflip] = 0;
		}


		if(vexRT[Btn8L] == 1)
		{
			motor[claw] = 100;
		}
		else if (vexRT[Btn8R] == 1)
		{
			motor[claw] = -100;
		}

		else
		{
			motor[claw] = 0;
		}

		if(vexRT[Btn5U] == 1)
		{
			motor[flipmotor] = 90;
		}

		else if (vexRT[Btn5D] == 1)
		{
			motor[flipmotor] = -90;
		}

		else
		{
			motor[flipmotor] = 0;
		}

		if(vexRT[Btn6U] == 1)
		{
			motor[liftright] = 100;
		}

		else if (vexRT[Btn6D] == 1)
		{
			motor[liftright] = -50;
		}

		else
		{
			motor[liftright] = 0;
		}





		if(vexRT[Btn6U] == 1)
		{
			motor[liftleft] = 100;
		}

		else if (vexRT[Btn6D] == 1)
		{
			motor[liftleft] = -50;
		}

			else
			{
				motor[liftleft] = 0;
			}

		}
	}
